### ISSUE TITLE
botsing-parallel v0.0.1 requirements

### ISSUE THREAD

**Issue by xdevroey** [STAMP-project/botsing-parallel#1] opened 2019-05-29 13:26 UTC
The purpose of this tool is to allow parallel execution of botsing-reproduction in order to generate a test case able to reproduce a given stack trace for a given project.

### Requirements

- For a given stack trace and a given project, botsing-parallel shall run in parallel ***N*** botsing-reproduction instances and try to reproduce each frame of the stack trace a given ***X*** number of times. 
- botsing-parallel shall start by trying to reproduce the lower frames of the stack trace. 
- botsing-parallel shall allow having a configuration file (respecting `.properties` format like [this example](https://github.com/STAMP-project/botsing/blob/master/botsing-reproduction/src/main/resources/config.properties)) with the additional optional parameters provided to botsing-reproduction instance. This file is optional and botsing-parallel shall work without it as well.
- botsing-parallel shall support to be called both with a classpath that respects botsing-reproduction command line format ([`project_cp`](https://stamp-project.github.io/botsing/pages/crashreproduction.html)) and with [Maven projects](https://github.com/STAMP-project/botsing/tree/master/botsing-maven). (I suppose that the simple thing to do here is to define two scripts, one for running botsing-parallel with the command line version and one for running botsing-parallel with the Maven plugin version)

#### Example

For the following stack trace with three frames:
```
java.lang.ArrayIndexOutOfBoundsException:
	at org.apache.commons.lang3.time.FastDateParser.toArray(FastDateParser.java:413)
	at org.apache.commons.lang3.time.FastDateParser.getDisplayNames(FastDateParser.java:381)
	at org.apache.commons.lang3.time.FastDateParser$TextStrategy.addRegex(FastDateParser.java:664)
```

Calling botsing-parallel with ***N = 2*** (2 instances in parallel) and ***X = 3***, will call botsing-reproduction in the following order:
- botsing-reproduction on frames 1 and 2
- botsing-reproduction on frames 3 and 1
- botsing-reproduction on frames 2 and 3
- botsing-reproduction on frames 1 and 2
- botsing-reproduction on frames 3

Of course, if for one of the frames, the botsing-reproduction instance finishes sooner, botsing-parallel can proceed to the next frame.

**Comment by xdevroey** [comment] 2019-05-29 13:28
Hi @pasquy73, here is the first set of requirements for botsing-parallel. Maybe we should ask use case providers to take a look at it to see if it fits their needs.

**Comment by xdevroey** [comment] 2019-05-29 13:29
A previous bash script that @pderakhshanfar has developed for our empirical evaluations is available [here](https://github.com/STAMP-project/ExRunner-bash/blob/phase2/crash-reproduction-no-seeding/main.sh). Maybe you can take a look at it to help you developing botsing-parallel.

**Comment by pasquy73** [comment] 2019-06-05 12:28
Hi @xdevroey, 
I have had a look to your example and I am wondering if this kind of parallelization is finalized to speed-up the runtime amplification, in particular the X parameter.
Could you explain how you get this objective?

**Comment by xdevroey** [comment] 2019-06-05 12:52
Hi @pasquy73, as you know, Botsing is a best effort tool. It uses a meta-heuristic and the results may be different from one execution from the other. So if Botsing cannot reproduce a frame from the first time, maybe it can do it if we try again. The ***X*** parameter is that: the number of times the user wants to try per frame. 

One thing I forgot in the example: if one frame could be reproduced in the sequence I gave, that frame does not need to be retry afterward. For example, if Botsing can reproduce frame 1 in the first try, the sequence becomes: 
- botsing-reproduction on frames 1 and 2
- botsing-reproduction on frames 3 and ~1~ 2
- botsing-reproduction on frames ~2~ 3 and ~3~ 2
- botsing-reproduction on frames ~2~ 3

**Comment by pasquy73** [comment] 2019-06-05 15:55
Hi @xdevroey, I implemented a first solution about the first example; N threads replicated X times.
Of course, I can check if some frames are OK and bypass them; for example the frame 1 in the second example. 
In this case there is the possibility that 2 threads can run on the same frame in the same time.
For example N=2 on 3 frames: the reproduction starts with 2 threads: thread 1 for frame=1 and thread 2 for frame 2. Suppose that the execution for frame 2 and 3 is faster, in this case there is the possibility that the thread 2 ends (on frame 2 and 3) before thread 1, and so the thread 2 start again on frame 1

**Comment by xdevroey** [comment] 2019-06-06 08:17
> Hi @xdevroey, I implemented a first solution about the first example; N threads replicated X times.

Great, good news!

> Of course, I can check if some frames are OK and bypass them; for example the frame 1 in the second example. In this case there is the possibility that 2 threads can run on the same frame in the same time. For example N=2 on 3 frames: the reproduction starts with 2 threads: thread 1 for frame=1 and thread 2 for frame 2. Suppose that the execution for frame 2 and 3 is faster, in this case there is the possibility that the thread 2 ends (on frame 2 and 3) before thread 1, and so the thread 2 start again on frame 1

Yes, sure. The order in the example is indeed for the waiting queue, but if a thread goes faster, it can process to the next job. Yes, sure. The order in the example is indeed for the waiting queue, but if a thread goes faster, it can process to the next job.

**Comment by pasquy73** [comment] 2019-06-12 09:06
Hi @xdevroey, I'm trying to run my botsing-parallel and I'm using ExRunner-bash data: for example crash_log = ExRunner-bash\crashes\lang\LANG-9b\LANG-9b.log and project_cp = ExRunner-bash\bins\lang\9b\bin. If I use target_frame = 3 the botsing-reproduction takes a lot of time (for frame 3) and many resources (after 3 hours the task is not completed yet). Instead botsing-reproduction for frames 1 and 2 are ok. Is it normal or I'm wrong something.

**Comment by pasquy73** [comment] 2019-06-13 12:46
Hi @xdevroey, I solved the issue about to run N thread (botsing-reproduction) using the same frame. Simply any threads wait until the execution finish of previous thread.

**Comment by pasquy73** [comment] 2019-06-13 12:57
Just for information, all results are stored in the `test_dir` folder; but in the parallel case, we have more reproductions because we can use more `target_frame` and the results can be overwrite, so I have to use different `test_dir` folders; I alway append at the end of test_dir param the `-<target_frame>`. For example for `target_frame=3`, we have these directories: 

- `crash-reproduction-tests-1`,

-  `crash-reproduction-tests-2` 

- and `crash-reproduction-tests-3`.

**Comment by pasquy73** [comment] 2019-09-02 12:43
I think I can close this issue.

**Closed as completed by pasquy73** 2019-09-02 12:43 UTC
Labels: enhancement
